### ISSUE TITLE
Failing to install tool because of nuget

### ISSUE THREAD

**Issue by tomcurran** [jonathanpeppers/boots#13]
I'm getting the following trying to use boots via the AzDO task. Any ideas why the tool would be failing to install? Should I change the dotnet core version or something? Any ideas?

> sr/local/bin/dotnet tool install boots --tool-path=/Users/vsts/agent/2.155.1/work/_temp/boots-tool
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error : Failed to retrieve information about 'boots' from remote source 'https://***.pkgs.visualstudio.com/_packaging/164a5357-b315-4246-bb30-325322e6ed24/nuget/v3/flat2/boots/index.json'. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/1phhlwap.qw4/restore.csproj]
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/1phhlwap.qw4/restore.csproj]
> The tool package could not be restored.
> Tool 'boots' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
>

**Comment by jonathanpeppers** [comment]
I think you can specify `version`:
```yaml
steps:
- task: Boots@1
  displayName: Install Xamarin.Android
  inputs:
    uri: https://aka.ms/xamarin-android-commercial-d16-2-window
    version: 1.0.0.291
```
https://github.com/pjcollins/azure-web-extensions/blob/21daadae6badc865cb15b31877a550880d73bb63/Tasks/Boots/task.json#L24-L31

Does that work?

**Comment by tomcurran** [comment]
That didn't help. It looks like its trying to use a private nuget feed which is used in different part of the pipeline, which it can't authenticate with. Really strange.

> sr/local/bin/dotnet tool install boots --tool-path=/Users/vsts/agent/2.155.1/work/_temp/boots-1.0.0.291 --version=1.0.0.291
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error : Unable to load the service index for source https://***.pkgs.visualstudio.com/_packaging/Mobile/nuget/v3/index.json. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hl5ocrw0.onl/restore.csproj]
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hl5ocrw0.onl/restore.csproj]
> The tool package could not be restored.
> Tool 'boots' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.

I also tried it in a new pipeline and the tool installed but the install failed

> Tool 'boots' (version '1.0.0.291') was successfully installed.
> sers/vsts/agent/2.155.1/work/_temp/boots-1.0.0.291/boots https://aka.ms/xamarin-android-commercial-d16-2-window
> boots 1.0.0.291
> Downloading https://aka.ms/xamarin-android-commercial-d16-2-window
> Writing to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e1simac3.3gh.pkg
> installer: Error - the package path specified was invalid: '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e1simac3.3gh.pkg'.
> 
> 
> Deleting /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e1simac3.3gh.pkg
> 
> Unhandled Exception: System.Exception: '/usr/bin/sudo' with arguments '/usr/sbin/installer -pkg "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e1simac3.3gh.pkg" -target / -verbose' exited with code 1
>    at Boots.Core.AsyncProcess.RunAsync(CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/AsyncProcess.cs:line 69
>    at Boots.Core.PkgInstaller.Install(String file, CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/PkgInstaller.cs:line 26
>    at Boots.Core.Bootstrapper.Install(CancellationToken token) in /Users/vsts/agent/2.154.3/work/1/s/Boots.Core/Bootstrapper.cs:line 31
>    at Boots.Program.Main(String[] args) in /Users/vsts/agent/2.154.3/work/1/s/Boots/Program.cs:line 24
>    at Boots.Program.<Main>(String[] args)

Don't think it should effect this but I'm using the classic editor in AzDO not a YAML file.

**Comment by jonathanpeppers** [comment]
If you use a plain `script` step, does it do the same thing?
```
variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
steps:
- script: |
    dotnet tool install --global boots
    boots https://aka.ms/xamarin-android-commercial-d16-2-windows
```
I don't know what the UI equivalent looks like if you are not using yaml.

**Comment by tomcurran** [comment]
Yeah the error message stays the same

> in/bash --noprofile --norc /Users/vsts/agent/2.155.1/work/_temp/69b30502-06d8-4375-81ef-44f5040e5fc7.sh
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error : Unable to load the service index for source https://***.pkgs.visualstudio.com/_packaging/Mobile/nuget/v3/index.json. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ndbcncyj.43q/restore.csproj]
> /Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ndbcncyj.43q/restore.csproj]
> The tool package could not be restored.
> Tool 'boots' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.

In the separate pipeline to isolate other things it changed to

> in/bash --noprofile --norc /Users/vsts/agent/2.155.1/work/_temp/7aabe1d5-8132-40dd-b846-51c7986c2f2b.sh
> + boots https://aka.ms/xamarin-android-commercial-d16-2-windows
> A fatal error occurred, the required library libhostfxr.dylib could not be found.
> If this is a self-contained application, that library should exist in [/Users/vsts/.dotnet/tools/.store/boots/1.0.0.291/boots/1.0.0.291/tools/netcoreapp2.1/any/].
> If this is a framework-dependent application, install the runtime in the default location [/usr/local/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

**Comment by tomcurran** [comment]
I'm running on macos so changed the file to https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.3/72cb587a39c12dfaa20cd5a0b1eb60a908ff88a6/1/package/xamarin.ios-12.14.0.113.pkg but the results were the same.

**Comment by jonathanpeppers** [comment]
So you're not even getting to the point where it installed `boots` at all:
```
/Users/vsts/.dotnet/sdk/2.2.105/NuGet.targets(114,5): error : Unable to load the service index for source https://***.pkgs.visualstudio.com/_packaging/Mobile/nuget/v3/index.json.
```
This is the output from `dotnet tool install --global boots`.

I use boots to build boots. But in this repo, I install a version of .NET Core: https://github.com/jonathanpeppers/boots/blob/2a757e7318424300a605ab2de4e1263bc799e0b5/azure-pipelines.yml#L46-L49

I just kicked off a build to see if things are still working: https://jopepper.visualstudio.com/Jon%20Peppers%20OSS/_build/results?buildId=331

**Comment by jonathanpeppers** [comment]
Here is the spot showing what it looks like if it is working: https://jopepper.visualstudio.com/Jon%20Peppers%20OSS/_build/results?buildId=331&view=logs&jobId=a82d9e72-1de4-5bd6-c188-90296135479e&taskId=8401ef5e-51a7-5daa-2c28-fe150f002214&lineStart=9&lineEnd=15&colStart=1&colEnd=77

```
[command]/Users/vsts/hostedtoolcache/dotnet/dotnet tool install boots --tool-path=/Users/vsts/agent/2.155.1/work/_temp/boots-tool
You can invoke the tool using the following command: boots
Tool 'boots' (version '1.0.0.291') was successfully installed.
[command]/Users/vsts/agent/2.155.1/work/_temp/boots-tool/boots https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.189.macos10.xamarin.universal.pkg
boots 1.0.0.291
Downloading https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.189.macos10.xamarin.universal.pkg
Writing to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/2a0aho31.woe.pkg
```
Is your build running on the Hosted Mac Pool?

**Comment by tomcurran** [comment]
Yeah, I'm using macOS-10.14 hosted agents. Looks like this might be a dotnet tool installation issue and not specific to boots. Not sure what to do though. Thanks for your help.

**Comment by tomcurran** [comment]
@jonathanpeppers I found people with a similar issue https://github.com/dotnet/cli/issues/9586 As https://github.com/dotnet/cli/issues/9586#issuecomment-484585146 suggested I had to override the install tools command to provide it with a nuget config file which only referenced nuget.org to essentially remove my private sources. It's pretty strange because the private nuget sources config file was only referenced much later in the build pipeline but the dotnet tools install command seemed to already know about it. As there was no way to override the nuget config of the install command within the boots task I wasn't able to use the task but calling the commands manually things worked out. This is roughly what I ended up using

```
steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 2.2.402'
  inputs:
    version: 2.2.402

- task: eliostruyf.build-task.custom-build-task.file-creator@5
  displayName: 'Create temporary nuget config'
  inputs:
    filepath: '$(Agent.TempDirectory)/NuGet.config'
    filecontent: |
     <?xml version="1.0" encoding="utf-8"?>
     <configuration>
       <packageSources>
         <clear />
         <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
       </packageSources>
     </configuration>

- task: DotNetCoreCLI@2
  displayName: 'Install boots'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global boots --configfile $(Agent.TempDirectory)/NuGet.config'

- bash: 'boots https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/b02da292bfe129d2d89bbcc2724810efbc33286f/317/package/xamarin.ios-13.0.0.19.pkg'
  displayName: 'Install Xamarin.iOS'
```
