### ISSUE TITLE
Boots doesn't work with DotNet5

### ISSUE THREAD

**Issue by SaqibS** [jonathanpeppers/boots#55]
1. I install DotNet5
2. I install boots
3. I try to run Boots, but get an error about DotNet3.0 not being installed.

While it would be relatively trivial to install DotNet3 on the build server, it seems unnecessary since surely DotNet5 is backwards compatible, and indeed I used DotNet5 to install Boots.

Any tips appreciated.

Output below:

You can invoke the tool using the following command: boots
Tool 'boots' (version '1.0.3.527') was successfully installed.

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
- The following frameworks were found:
5.0.1 at [/Users/runner/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=osx.10.15-x64

**Comment by jonathanpeppers** [comment]
Is this running on Azure DevOps? What agent pool is it?

On Azure DevOps, last I checked `macos-latest` and `windows-latest` were both working, but maybe an update to the image broke this?

**Comment by SaqibS** [comment]
Yes, this is on Azure Dev Ops. We're using the macOS-10.15 image.

Our YAML includes the following two tasks:

```yaml
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(DotNetCoreVersion)'
      inputs:
        version: '$(DotNetCoreVersion)'

    - bash: 'dotnet tool install --global --ignore-failed-sources boots && boots --stable Mono && boots --stable Xamarin.iOS'
      displayName: 'Install latest stable Mono and Xamarin.iOS'
```

In the failing version, `DotNetCoreVersion` is set to 5.x.
